// SPDX-License-Identifier: MIT
/**
 * YAML emitter for the Home Assistant adapter.
 *
 * Hand-rolls a deterministic Home Assistant `themes.yaml` document from the Turbo
 * theme registry. js-yaml is intentionally not used at runtime so the adapter has
 * no serialization dependency; tests parse the output with js-yaml to validate it.
 */

import { flavors } from '@lgtm-hq/turbo-themes-core';
import { mapTokensToHomeAssistant } from './mapping.js';
import { renderKey, renderValue } from './yaml.js';

const HEADER = [
  '# Generated by @lgtm-hq/turbo-themes/adapters/home-assistant',
  '# Do not edit by hand.',
].join('\n');

/**
 * Render a variable mapping as indented `key: "value"` lines.
 *
 * The mapping preserves {@link REQUIRED_KEYS} order (produced by
 * {@link mapTokensToHomeAssistant}), so iterating its entries is deterministic.
 *
 * @param mapping - Variable name → value record.
 * @param indent - Leading indent applied to every line.
 */
function renderMapping(mapping: Record<string, string>, indent: string): string[] {
  return Object.entries(mapping).map(
    ([key, value]) => `${indent}${renderKey(key)}: ${renderValue(value)}`,
  );
}

/** Emit a single flat theme block (top-level keys only). */
function emitFlatTheme(name: string, mapping: Record<string, string>): string {
  return [`${renderKey(name)}:`, ...renderMapping(mapping, '  ')].join('\n');
}

/**
 * Generate the Home Assistant themes YAML document.
 *
 * Flat themes are emitted first, sorted alphabetically by theme id for
 * determinism.
 *
 * @returns The full YAML document as a string.
 */
export function generateHomeAssistantThemes(): string {
  const sorted = [...flavors].sort((a, b) => a.id.localeCompare(b.id, 'en'));
  const blocks = sorted.map((flavor) =>
    emitFlatTheme(flavor.label, mapTokensToHomeAssistant(flavor.tokens)),
  );

  return `${HEADER}\n${blocks.join('\n')}\n`;
}
