import { describe, expect, it } from 'vitest';
import yaml from 'js-yaml';
import { flavors } from '@lgtm-hq/turbo-themes-core';
import { generateHomeAssistantThemes } from '../src/emitter.js';
import { REQUIRED_KEYS } from '../src/mapping.js';
import { AUTO_THEME_PAIRINGS } from '../src/pairings.js';

const output = generateHomeAssistantThemes();
const parsed = yaml.load(output) as Record<string, Record<string, unknown>>;

describe('generateHomeAssistantThemes', () => {
  it('starts with the generated-file header', () => {
    expect(output.startsWith('# Generated by @lgtm-hq/turbo-themes/adapters/home-assistant\n')).toBe(
      true,
    );
    expect(output).toContain('# Do not edit by hand.');
  });

  it('produces a parseable YAML mapping', () => {
    expect(parsed).toBeTypeOf('object');
    expect(parsed).not.toBeNull();
  });

  it('is deterministic across invocations', () => {
    expect(generateHomeAssistantThemes()).toBe(output);
  });

  it('includes a top-level theme for every flat flavor label', () => {
    for (const flavor of flavors) {
      expect(parsed[flavor.label], flavor.label).toBeDefined();
    }
  });

  it('gives every flat theme at least 80 keys covering REQUIRED_KEYS', () => {
    for (const flavor of flavors) {
      const theme = parsed[flavor.label];
      expect(theme, flavor.label).toBeDefined();
      const keys = Object.keys(theme as Record<string, unknown>);
      expect(keys.length, flavor.label).toBeGreaterThanOrEqual(80);
      for (const required of REQUIRED_KEYS) {
        expect(keys, `${flavor.label} → ${required}`).toContain(required);
      }
    }
  });

  it('emits concrete values with no CSS var() references', () => {
    expect(output).not.toContain('var(');
  });

  it('emits exactly 48 top-level themes (40 flat + 8 auto)', () => {
    expect(Object.keys(parsed)).toHaveLength(48);
    expect(flavors).toHaveLength(40);
    expect(AUTO_THEME_PAIRINGS).toHaveLength(8);
  });

  it('gives each auto theme dark and light modes with full mappings', () => {
    for (const pairing of AUTO_THEME_PAIRINGS) {
      const theme = parsed[pairing.name] as Record<string, unknown>;
      expect(theme, pairing.name).toBeDefined();

      // Top-level keys mirror the dark mapping.
      for (const required of REQUIRED_KEYS) {
        expect(theme, `${pairing.name} → ${required}`).toHaveProperty(required);
      }

      const modes = theme.modes as { dark?: Record<string, unknown>; light?: Record<string, unknown> };
      expect(modes, `${pairing.name} modes`).toBeDefined();
      expect(Object.keys(modes.dark ?? {}), `${pairing.name} modes.dark`).toEqual([...REQUIRED_KEYS]);
      expect(Object.keys(modes.light ?? {}), `${pairing.name} modes.light`).toEqual([
        ...REQUIRED_KEYS,
      ]);
    }
  });

  it('matches the committed full-document snapshot', () => {
    expect(output).toMatchSnapshot();
  });
});
