import { describe, expect, it } from 'vitest';
import yaml from 'js-yaml';
import { flavors } from '@lgtm-hq/turbo-themes-core';
import { generateHomeAssistantThemes } from '../src/emitter.js';
import { REQUIRED_KEYS } from '../src/mapping.js';

const output = generateHomeAssistantThemes();
const parsed = yaml.load(output) as Record<string, Record<string, unknown>>;

describe('generateHomeAssistantThemes', () => {
  it('starts with the generated-file header', () => {
    expect(output.startsWith('# Generated by @lgtm-hq/turbo-themes/adapters/home-assistant\n')).toBe(
      true,
    );
    expect(output).toContain('# Do not edit by hand.');
  });

  it('produces a parseable YAML mapping', () => {
    expect(parsed).toBeTypeOf('object');
    expect(parsed).not.toBeNull();
  });

  it('is deterministic across invocations', () => {
    expect(generateHomeAssistantThemes()).toBe(output);
  });

  it('includes a top-level theme for every flat flavor label', () => {
    for (const flavor of flavors) {
      expect(parsed[flavor.label], flavor.label).toBeDefined();
    }
  });

  it('gives every flat theme at least 80 keys covering REQUIRED_KEYS', () => {
    for (const flavor of flavors) {
      const theme = parsed[flavor.label];
      expect(theme, flavor.label).toBeDefined();
      const keys = Object.keys(theme as Record<string, unknown>);
      expect(keys.length, flavor.label).toBeGreaterThanOrEqual(80);
      for (const required of REQUIRED_KEYS) {
        expect(keys, `${flavor.label} → ${required}`).toContain(required);
      }
    }
  });

  it('emits concrete values with no CSS var() references', () => {
    expect(output).not.toContain('var(');
  });
});
