// SPDX-License-Identifier: MIT
/**
 * Style Dictionary configuration for Turbo Themes
 *
 * Transforms W3C Design Tokens to platform-specific formats
 * while preserving $type metadata for tooling support.
 *
 * Source tokens: `dist/tokens/style-dictionary/*.json`
 * (Generated by `scripts/prepare-style-dictionary.mjs`)
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { allTransforms } from './style-dictionary/transforms.mjs';
import { allFormats } from './style-dictionary/formats.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default {
  source: ['dist/tokens/style-dictionary/*.json'],

  log: {
    verbosity: 'warn',
  },

  // Register custom transforms and formats
  hooks: {
    transforms: Object.fromEntries(allTransforms.map((t) => [t.name, t])),
    formats: Object.fromEntries(allFormats.map((f) => [f.name, f])),
  },

  platforms: {
    // CSS custom properties
    css: {
      transformGroup: 'css',
      transforms: ['name/kebab'],
      buildPath: 'assets/css/',
      files: [
        {
          destination: 'turbo-core.css',
          format: 'css/variables-with-metadata',
          options: {
            selector: ':root',
            prefix: 'turbo',
          },
        },
      ],
    },

    // SCSS map for Sass consumers
    scss: {
      transformGroup: 'scss',
      transforms: ['name/kebab'],
      buildPath: 'assets/scss/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/map-with-types',
          options: {
            mapName: 'turbo-tokens',
          },
        },
      ],
    },

    // JavaScript ESM for JS/TS consumers
    js: {
      transformGroup: 'js',
      transforms: ['name/kebab'],
      buildPath: 'packages/core/src/themes/generated/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/esm-with-types',
          options: {
            exportName: 'tokens',
          },
        },
      ],
    },

    // JSON with types for tooling
    json: {
      transformGroup: 'js',
      transforms: ['name/kebab'],
      buildPath: 'dist/tokens/',
      files: [
        {
          destination: 'tokens-typed.json',
          format: 'json/with-types',
        },
      ],
    },

    // Python dataclass (if needed)
    python: {
      transformGroup: 'js',
      transforms: ['name/kebab'],
      buildPath: 'python/src/turbo_themes/generated/',
      files: [
        {
          destination: 'tokens.py',
          format: 'python/dataclass',
          options: {
            className: 'TurboTokens',
          },
        },
      ],
    },

    // Swift struct (if needed)
    swift: {
      transformGroup: 'js',
      transforms: ['name/kebab'],
      buildPath: 'swift/Sources/TurboThemes/Generated/',
      files: [
        {
          destination: 'Tokens.swift',
          format: 'swift/struct',
          options: {
            structName: 'TurboTokens',
          },
        },
      ],
    },
  },
};
