/* SPDX-License-Identifier: MIT */
/**
 * Generate .css.d.ts shims for every shipped CSS file.
 *
 * Each shim is a side-effect-only module declaration:
 *
 *   export {};
 *
 * This satisfies TypeScript's `noUncheckedSideEffectImports` (TS 5.6+) check
 * for consumers doing `import "@lgtm-hq/turbo-themes/css"` and the other
 * CSS subpath imports declared in the root package.json exports map.
 *
 * The exports map points its `types` condition at these shims — see the
 * ./css*, ./adapters/bulma.css entries in ../package.json.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const SHIM_CONTENT = `// Generated by scripts/generate-css-dts.mjs — do not edit.
// Side-effect-only CSS module. Allows \`import "<pkg>/<subpath>"\` under
// TypeScript's noUncheckedSideEffectImports check.
export {};
`;

// Directories whose *.css files are exposed via package.json "exports".
// Each entry is relative to the project root.
const CSS_DIRS = [
  'packages/css/dist',
  'packages/css/dist/components',
  'packages/css/dist/themes',
  'packages/adapters/bulma/dist',
];

function listCssFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.css'))
    .map((entry) => path.join(dir, entry.name));
}

function writeShim(cssPath) {
  const shimPath = `${cssPath}.d.ts`;
  fs.writeFileSync(shimPath, SHIM_CONTENT, 'utf8');
  return shimPath;
}

function main() {
  let written = 0;
  for (const rel of CSS_DIRS) {
    const absDir = path.join(projectRoot, rel);
    const cssFiles = listCssFiles(absDir);
    for (const cssPath of cssFiles) {
      const shimPath = writeShim(cssPath);
      const relShim = path.relative(projectRoot, shimPath);
      console.log(`  ${relShim}`);
      written += 1;
    }
  }

  if (written === 0) {
    console.error('No CSS files found — did the CSS build run first?');
    process.exit(1);
  }

  console.log(`\nGenerated ${written} .css.d.ts shim(s).`);
}

main();
