/**
 * Verifies that CSS subpath exports carry a `types` condition and that the
 * referenced .d.ts shims exist on disk and are valid side-effect module
 * declarations.
 *
 * Regression guard for TS 5.6+ `noUncheckedSideEffectImports`:
 * consumers doing `import "@lgtm-hq/turbo-themes/css"` under strict TS
 * configs must be able to resolve a type declaration.
 */
import { readFileSync, readdirSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { describe, it, expect } from 'vitest';

type ExportsValue = string | { types?: string; default?: string; import?: string };
type ExportsMap = Record<string, ExportsValue>;

const pkg = JSON.parse(readFileSync('package.json', 'utf-8')) as {
  exports: ExportsMap;
};

/**
 * Subpath keys in the exports map that map to CSS files and therefore need
 * a `types` condition with a .d.ts shim.
 */
const CSS_SUBPATH_KEYS = Object.entries(pkg.exports)
  .filter(([key, value]) => {
    // Only keys under ./css* or ./adapters/*.css
    const isCssSubpath = key.startsWith('./css') || key.endsWith('.css');
    if (!isCssSubpath) return false;
    // The target resolves to a .css file (direct or wildcard)
    if (typeof value === 'string') return value.endsWith('.css') || value.includes('/*');
    const target = value.default ?? value.import;
    return target ? target.endsWith('.css') || target.includes('/*') : false;
  })
  .map(([key]) => key);

describe('CSS subpath exports have `types` conditions', () => {
  it('discovers CSS subpath exports', () => {
    expect(CSS_SUBPATH_KEYS.length).toBeGreaterThan(0);
  });

  for (const key of CSS_SUBPATH_KEYS) {
    it(`${key} exposes a types condition`, () => {
      const value = pkg.exports[key];
      expect(typeof value, `${key} must be a conditional exports object`).toBe('object');
      expect((value as { types?: string }).types, `${key} must have a types field`).toBeDefined();
    });
  }
});

describe('CSS subpath `types` targets resolve to shim files', () => {
  for (const key of CSS_SUBPATH_KEYS) {
    const value = pkg.exports[key];
    if (typeof value !== 'object' || !value.types) continue;

    const typesPath = value.types.replace(/^\.\//, '');
    const isWildcard = typesPath.includes('*');

    if (!isWildcard) {
      it(`${key} → ${typesPath} exists`, () => {
        expect(existsSync(typesPath), `${typesPath} should be generated by scripts/generate-css-dts.mjs`).toBe(true);
      });

      it(`${key} shim is a valid side-effect module`, () => {
        const content = readFileSync(typesPath, 'utf-8');
        expect(content, `${typesPath} must contain an empty export statement`).toMatch(/export\s*\{\s*\}\s*;/);
      });
    } else {
      // Wildcard: check that every .css file in the source dir has a matching .css.d.ts
      const dir = dirname(typesPath);
      it(`${key} → ${typesPath} has shim for every CSS file in ${dir}`, () => {
        expect(existsSync(dir), `${dir} should exist`).toBe(true);
        const entries = readdirSync(dir);
        const cssFiles = entries.filter((f) => f.endsWith('.css'));
        const dtsFiles = new Set(entries.filter((f) => f.endsWith('.css.d.ts')));
        expect(cssFiles.length).toBeGreaterThan(0);
        for (const cssFile of cssFiles) {
          expect(dtsFiles.has(`${cssFile}.d.ts`), `missing shim for ${join(dir, cssFile)}`).toBe(true);
        }
      });
    }
  }
});
