---
name: Release - Version PR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-version-pr-${{ github.repository }}
  cancel-in-progress: false

jobs:
  version-pr:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-release-version-pr.yml@375d104f6ca707f4f35344170a42bf901a617a9f # v0.15.0
    with:
      max-bump: minor
      auto-merge: true
      auto-merge-patch-only: true
      version-update-script: scripts/ci/update-version-files.sh
      tooling-ref: "375d104f6ca707f4f35344170a42bf901a617a9f"
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
    permissions:
      contents: write
      pull-requests: write
